#!/bin/bash
set -e

expand_path() {
  mkdir -p `dirname "$1"`
  cd `dirname "$1"`
  echo $PWD/`basename "$1"`
}

CONFIG_PATH=`expand_path $1`
cd `dirname $0`/..
. /etc/lsb-release

if [ `id -u` != "0" ]; then
  fail "Please run this script as root: sudo $0 $@"
fi

if [ -z "$CONFIG_PATH" ]; then
  fail "Missing the first argument: the path to the config file"
fi

if ! [ -f "$CONFIG_PATH" ]; then
  fail "Config file not found at $CONFIG_PATH"
fi

if ! [ -f /etc/apt/sources.list.d/rquillo-ansible-$DISTRIB_CODENAME.list ]; then
  echo "Install ansible"
  apt-get install -qy python-software-properties
  apt-add-repository -y ppa:rquillo/ansible
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -qy ansible
fi

exec ansible-playbook -i localhost, -e "src_dir=$PWD config_path=$CONFIG_PATH" script/install.yml
