#!/bin/bash
set -e

expand_path() {
  mkdir -p `dirname "$1"`
  cd `dirname "$1"`
  echo $PWD/`basename "$1"`
}

CACHE_DIR=`expand_path "$1"`
DESTDIR=`expand_path "$2"`
cd `dirname $0`/..
. /etc/lsb-release

if [ -z "$DESTDIR" ]; then
  fail "Missing the first argument: the destination path"
fi

if ! [ -f /etc/apt/sources.list.d/rquillo-ansible-$DISTRIB_CODENAME.list ]; then
  echo "Install ansible"
  apt-get install -qy python-software-properties
  apt-add-repository -y ppa:rquillo/ansible
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -qy ansible
fi

exec ansible-playbook -i localhost, -e "src_dir=$PWD dest_dir=$DESTDIR cache_dir=$CACHE_DIR" script/slugify.yml
