#!/usr/bin/env bash

set -e

. `dirname $0`/ploy-lib.sh

CACHE_DIR=`expand_path "$1"`
DESTDIR=`expand_path "$2"`

if [ -z "$DESTDIR" ]; then
  fail "Missing the first argument: the destination path"
fi

cd `dirname $0`/..

## Build dependencies ##
depend Dependfile build

## Copying the release files ##
rm -rf "$DESTDIR"
mkdir -p "$DESTDIR"
cp -r * "$DESTDIR"
cd "$DESTDIR"

## Installing the runtime dependencies ##
bundle install --path=vendor --deployment --binstubs=bin --without="development test"
export LIBRARIAN_CHEF_PATH=vendor/cookbooks
export LIBRARIAN_CHEF_TMP="$CACHE_DIR/librarian"
export LIBRARIAN_CHEF_INSTALL__STRIP_DOT_GIT=1
librarian-chef install
